# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['gui.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'groq',
        'rich',
        'rich.console',
        'rich.panel',
        'ddgs',
        'docx',
        'fpdf',
        'pypdf',
        'psutil',
        'dotenv',
        'sqlite3',
        'tkinter',
        'tkinter.scrolledtext',
        'tkinter.messagebox',
        'imaplib',
        'smtplib',
        'email',
        'email.mime.text',
        'email.header',
        'playwright',
        'playwright.sync_api',
        'greenlet',
        'openpyxl',
        'openpyxl.styles',
        'pyttsx3',
        'PIL',
        'PIL.Image',
        'PIL.ImageGrab',
        'zipfile',
        'secrets',
        'socket',
        'tools.files',
        'tools.documents',
        'tools.search',
        'tools.system',
        'tools.memory',
        'tools.email_tool',
        'tools.browser',
        'tools.voice',
        'tools.notifications',
        'tools.excel',
        'tools.clipboard',
        'tools.utils',
        'tools.archive',
        'tools.image_tool',
        'tools.meteo',
        'tools.translator',
        'tools.qrcode_tool',
        'tools.voice_recognition',
        'tools.scheduler',
        'tools.stats',
        'tools.updater',
        'tools.license',
        'tools.computer_settings',
        'tools.youtube_tool',
        'tools.flight_finder',
        'tools.screen_vision',
        'tools.planner',
        'deep_translator',
        'qrcode',
        'speech_recognition',
        'bs4',
        'fitz',
        'pymupdf',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Amah Agent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='amah.ico',
)
